#!/bin/bash

echo "Mise à jour des paquets..."
sudo apt update && sudo apt upgrade -y

echo "Installation de Docker..."
sudo apt install docker.io -y

echo "Installation de Docker Compose..."
sudo apt install docker-compose -y

echo "Lancement de Docker et configuration de Portainer..."
sudo docker run -d -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest

echo "Docker et Portainer ont été installés avec succès."
